### PR TITLE
Upgrade to jte 3 and use maven plugin to generate test template classes

### LINKED ISSUE #22: Precompiled Jte tests use generated output from test sources
The whole precompiled directory shouldn't be a part of test sources, e.g.:

https://github.com/javalin/javalin-rendering/blob/main/src/test/java/io/javalin/jte/precompiled/JtetestGenerated.java

These classes should be generated by Maven plugin:

https://github.com/casid/jte/blob/main/DOCUMENTATION.md#maven

### PR DESCRIPTION
**Pull request by casid**
This should resolve #22

### CODE REVIEW

**Comment by casid** [comment]
As expected, the Java 11 tests fail since jte 3 is compiled with Java 17.

@tipsy, @dzikoysk I don't like the extra complexity in the maven build script. Also, I had to disable the .kte tests, as it seems the maven kotlin compiler does not pickup generated test sources. At least I found no way to do that, but I'm not very experienced in Kotlin. Do you have an idea?

For sake of simplicity I would also be happy with just mergin the first commit (version bump) and call it a day.

**Comment by tipsy** [comment]
> As expected, the Java 11 tests fail since jte 3 is compiled with Java 17.

I can remove that soon :)

> @tipsy, @dzikoysk I don't like the extra complexity in the maven build script. Also, I had to disable the .kte tests, as it seems the maven kotlin compiler does not pickup generated test sources. At least I found no way to do that, but I'm not very experienced in Kotlin. Do you have an idea?
> For sake of simplicity I would also be happy with just merging the first commit (version bump) and call it a day.

I don't have any strong feelings on this, I'll leave it up to @dzikoysk to make his case.

**Comment by dzikoysk** [comment]
These tests pass for me with following addition:

* https://github.com/casid/javalin-rendering/pull/1

**Comment by casid** [comment]
Nice, thank you for the fix @dzikoysk

**Comment by tipsy** [comment]
I rebased this onto Java 17 now @casid, are you ready for review?

**Comment by casid** [comment]
Yes, I think this is ready :-)

**Comment by tipsy** [comment]
Looks great, thank you @casid !

**Pull request merged**
