### PR TITLE
Add module-info.java file

### PR DESCRIPTION
**Pull request by Dylan700**
Following #24, I have added a `module-info.java` file to the repository to modularize this project.

Unfortunately, 2 template engine libraries cannot be included since they are not modularized themselves, and do not contain automatic-module-name entries:
1. StringTemplate4
2. Velocity

However, this particular issue should only affect others using this project if they are using the java module system (non-modular projects using this dependency should be fine).

Furthermore, while this code does successfully compile with `mvn package`, I am receiving errors with the tests.

> [ERROR] /usr/src/mymaven/src/test/java/io/javalin/jte/PrecompileJteTestClasses.java:[17,55] cannot access gg.jte.CodeResolver
[ERROR]   class file for gg.jte.CodeResolver not found

I can successfully generate a `.jar` file with the module information by running ` mvn package -Dmaven.test.skip`, however, this is not a good solution to that problem.

### CODE REVIEW

**Comment by tipsy** [comment]
Unfortunately I'm not very experience with modules, but you can see what was done by @SentryMan for the main artifact: 

* https://github.com/javalin/javalin/pull/1908
* https://github.com/javalin/javalin/pull/1923

**Comment by Dylan700** [comment]
Thanks for the info, I've figured it out. Everything seems to be working fine on my end now.

**Comment by Dylan700** [comment]
> Great! Could you also add this at build time? (second PR I linked)
Sure, although are you sure this is necessary? When you say build time, do you mean generating/compiling the jar with `mvn package`? 
I have currently imported the generated jar and checked the module info with `jar --file=thejar.jar --describe-module` and it's working in my current modular project.

Let me know what you think.

**Comment by tipsy** [comment]
> Sure, although are you sure this is necessary? When you say build time, do you mean generating/compiling the jar with mvn package?

The project breaks in IntelliJ, so this is unfortunately required (see https://github.com/javalin/javalin/issues/1922)

**Comment by tipsy** [comment]
I have not actually tested this one though, but I assume it's going to be the same. If you can confirm that tests can still be run from IntelliJ, then this is not needed :)

**Comment by Dylan700** [comment]
> I have not actually tested this one though, but I assume it's going to be the same. If you can confirm that tests can still be run from IntelliJ, then this is not needed :)

Oh ok that makes sense, thanks. I do not usually use IntelliJ but I'll confirm this and get back to you when I get the chance.

**Comment by tipsy** [comment]
Are you testing it in intellij now? 😊

**Comment by Dylan700** [comment]
Hey @tipsy,

Yep, currently trying to sort this out 😆 

When I add the moditech package as per the second PR linked, I receive this error:
Screen Shot 2023-08-28 at 5 17 23 pm

It seems that particular plugin is not needed in our case?

Running the tests through a JUnit configuration in IntelliJ returns an error, however, setting up a configuration for maven works perfectly.
Screen Shot 2023-08-28 at 5 17 52 pm

Screen Shot 2023-08-28 at 5 19 30 pm

**Comment by tipsy** [comment]
> Running the tests through a JUnit configuration in IntelliJ returns an error, however, setting up a configuration for maven works perfectly.

Yeah, this is what we are trying to avoid by including it during build. Could you include the plugin?

**Comment by Dylan700** [comment]
Hi @tipsy,

I've added the moditech plugin. Since you're more familiar with the project, could you please check if this is working on your end before merging?

**Comment by Dylan700** [comment]
No worries at all @tipsy. I've just made that change, let me know if there's anything else.

**Comment by Dylan700** [comment]
Ah dang, what was the command you used for that? I'm not sure how maven works exactly, but I know that for gradle, the module-info.java file needs to be in the src folder.

If you go back to commit [0117ced](https://github.com/javalin/javalin-rendering/pull/25/commits/0117ced7b7c1a21242aca0d24cfdea6ed4e201dd), do you get the same error?

**Comment by tipsy** [comment]
I'll try later today!

**Comment by Dylan700** [comment]
Yeah, from my experience, IntelliJ is very temperamental. It definitely works via the command line in the previous commits, but not through IntelliJ. Hopefully SentryMan can help us out!

**Comment by SentryMan** [comment]
try adding `<useModulePath>false</useModulePath>` to surefire.

**Comment by Dylan700** [comment]
Thank @SentryMan, upon adding the suggested configuration, I realised that maybe the test class needs its own module.info file. This currently works with `mvn test` but I'll need @tipsy or yourself to confirm in IntelliJ (haven't got it installed right now).

**Comment by Dylan700** [comment]
Just removed the moditech plugin, the workflow checks should pass now. Might be worth adding another check for using this in a modular project too to ensure it definitely works.

**Comment by tipsy** [comment]
Without the plugin I think we would unfortunately be back at square one :/

I'll check it out locally to confirm.

**Comment by tipsy** [comment]
@Dylan700 I moved the `module-info.java` file to `meta/module-info.java`, and updated the plugin config:

```
<plugin>
    <groupId>org.moditect</groupId>
    <artifactId>moditect-maven-plugin</artifactId>
    <version>1.0.0.Final</version>
    <executions>
        <execution>
            <id>add-module-infos</id>
            <phase>package</phase>
            <goals>
                <goal>add-module-info</goal>
            </goals>
            <configuration>
                <overwriteExistingFiles>true</overwriteExistingFiles>
                <module>
                    <moduleInfoFile>./meta/module-info.java</moduleInfoFile>
                </module>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by tipsy** [comment]
Don't ask me why this works, but it does... 😓

**Comment by Dylan700** [comment]
@tipsy, awesome thanks heaps for confirming, haha as long as it's working I'm happy 😂

Did you put it into a commit?

**Comment by tipsy** [comment]
> Did you put it into a commit?

No, you can have that honor 😄

**Comment by Dylan700** [comment]
Haha ok, just added it back. Although the command `mvn package` doesn't seem to work now. Let me know how it looks on your end in IntelliJ. Not sure if I need to also move the module-info.java in both src and main folders or not.

**Comment by tipsy** [comment]
> Let me know how it looks on your end in IntelliJ. Not sure if I need to also move the module-info.java in both src and main folders or not.

Not seeing any commit yet 😄

**Comment by Dylan700** [comment]
> Not seeing any commit yet 😄
There we go 😆

**Comment by tipsy** [comment]
Still need to move the module-info.java file to meta/module-info.java. I think you can delete the one from the test folder.

**Comment by Dylan700** [comment]
@tipsy, done

**Comment by tipsy** [comment]
🤞

**Comment by tipsy** [comment]
Thanks @Dylan700 , looks like it went through!

**Comment by Dylan700** [comment]
Awesome, thanks for your assistance with this!

**Pull request merged**
